# Generated by Django 4.2.7 on 2025-06-29 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del tipo (ej: FWI, RAD)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo del tipo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto')),
                ('color', models.CharField(default='#3B82F6', help_text='Color hex para la interfaz', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del producto', max_length=200)),
                ('filename', models.CharField(help_text='Nombre del archivo original', max_length=255)),
                ('file_url', models.URLField(help_text='URL completa del archivo en el servidor OHMC')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('file_format', models.CharField(help_text='Formato del archivo (gif, png, jpg)', max_length=10)),
                ('generated_at', models.DateTimeField(help_text='Fecha y hora de generación del producto')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Válido desde', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Válido hasta', null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del producto')),
                ('region', models.CharField(blank=True, help_text='Región geográfica', max_length=100)),
                ('resolution', models.CharField(blank=True, help_text='Resolución espacial', max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text='Disponible para visualización')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Última verificación de disponibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Producto Meteorológico',
                'verbose_name_plural': 'Productos Meteorológicos',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_animation', models.BooleanField(default=False, help_text='Es una secuencia animada')),
                ('animation_speed', models.PositiveIntegerField(default=500, help_text='Velocidad de animación en ms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
                ('products', models.ManyToManyField(related_name='collections', to='products.weatherproduct')),
            ],
            options={
                'verbose_name': 'Colección de Productos',
                'verbose_name_plural': 'Colecciones de Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weatherproduct',
            index=models.Index(fields=['generated_at'], name='products_we_generat_572d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherproduct',
            index=models.Index(fields=['product_type', 'generated_at'], name='products_we_product_c6faa2_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherproduct',
            index=models.Index(fields=['is_available', 'generated_at'], name='products_we_is_avai_26c2de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherproduct',
            unique_together={('filename', 'product_type')},
        ),
    ]
