# Generated by Django 5.0.1 on 2025-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FWI', 'FWI'), ('GEI', 'GEI'), ('RAFAGA', 'RAFAGA'), ('WRF', 'WRF')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('url', models.URLField()),
                ('archivo', models.FileField(upload_to='productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tipo', 'nombre')},
            },
        ),
    ]
