# Generated by Django 5.0.1 on 2025-06-24 13:11

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='archivo',
            field=models.FileField(upload_to=productos.models.Producto.archivo_upload_to),
        ),
    ]
