# Generated by Django 5.0.1 on 2025-06-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_archivo'),
    ]

    operations = [
    ]
