# Generated by Django 4.2.7 on 2025-07-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
    ]
