# Generated by Django 4.2.7 on 2025-07-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_foto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('tipo_producto', 'variable', 'nombre_archivo')},
        ),
    ]
